name: terraform CI/CD - Manual Deploy

on:
  workflow_dispatch:

    inputs:
      terraform-action:
        description: 'Escolha a opção para aplicar as mudanças do Terraform'
        required: true
        default: Apply
        type: choice
        options:
          - Apply
          - Destroy

permissions:
  id-token: write
  contents: read

jobs:

  Apply:
    name: Terraform Plan for Apply
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform-action == 'Apply' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/terraform_setup
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra-dev/codes

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra-dev/codes


  Destroy:
    name: Terraform Plan for Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform-action == 'Destroy' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/terraform_setup

      - name: Terraform Plan for Destroy
        run: terraform plan -destroy -out=tfplan-destroy
        working-directory: ./infra-dev/codes

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan-destroy
        working-directory: ./infra-dev/codes